### ISSUE TITLE
How to handle hash in a route

### ISSUE THREAD

**Issue by rnons** [natefaubion/purescript-routing-duplex#1]
A continuation of https://github.com/slamdata/purescript-routing/issues/60#issuecomment-425948439

I'm trying to use `purescript-routing-duplex` and pushed to https://github.com/rnons/purescript-routing-issue-60/tree/duplex, but even this case doesn't work now

![image](https://user-images.githubusercontent.com/1082650/46325134-db50c180-c631-11e8-8655-1236ec599566.png)

Route is defined like this

```
data Region = East | West
derive instance eqRegion :: Eq Region
derive instance genericRegion :: Generic Region _

data PageRoute
  = Root
  | RegionRoute Region

derive instance eqPageRoute :: Eq PageRoute
derive instance genericPageRoute :: Generic PageRoute _

pageRoute :: RouteDuplex' PageRoute
pageRoute =
  root $ RDG.sum
    { "Root": noArgs
    , "RegionRoute": regionRoute
    }
  where
  regionRoute :: RouteDuplex' Region
  regionRoute = RDG.sum
    { "East": noArgs
    , "West": noArgs
    }
```

**Comment by rnons** [comment]
I changed `regionRoute` to

```
  regionRoute :: RouteDuplex' Region
  regionRoute = RDG.sum
    { "East": path "east" noArgs
    , "West": path "west" noArgs
    }
```

Now `http://localhost:8080/west` works, but `http://localhost:8080/west#abc` still not.

**Comment by natefaubion** [comment]
Fixed with https://github.com/natefaubion/purescript-routing-duplex/commit/343bf5ab4293e652b4df7dc85a5b654fffcda218

**Comment by natefaubion** [comment]
Thank you for the detailed reproduction.

**Comment by rnons** [comment]
Thanks for the fix, it works now.

I have another question, say if my `data Region` is a sum type of 40+ constructors, what's the best way to write `regionRoute`? I guess there is a `parse` function somewhere, but didn't find it

**Comment by natefaubion** [comment]
I'm not sure exactly what you mean by a `parse` function.

**Comment by rnons** [comment]
```
  regionRoute :: RouteDuplex' Region
  regionRoute = RDG.sum
    { "East": path "east" noArgs
    , "West": path "west" noArgs
    -- naturally I don't want to write 40+ lines of this
    }
```

I already have `readRegion :: String -> Maybe Region`, what I'm missing is how to use `readRegion` inside `regionRoute`

When I was using `purescript-routing`, I can write
```
regionMatcher :: Match Region
regionMatcher = Match \route ->
  case route of
    Cons (Path i) rs -> case readRegion i of
      Just East -> pure $ Tuple rs East
      _ -> invalid $ free $ Fail "Invalid region"
    _ -> invalid $ free ExpectedPathPart
```

**Comment by natefaubion** [comment]
You can use `as`.

```purescript
region :: RouteDuplex' String -> RouteDuplex' Region
region = as showRegion (readRegion >>> maybe (Left "Not a region") Right)

pageRoute :: RouteDuplex' PageRoute
pageRoute =
  root $ RDG.sum
    { "Root": noArgs
    , "RegionRoute": region segment
    }
```

**Comment by rnons** [comment]
Cool, thank you. Will give it a try.
