### ISSUE TITLE
Add operator for newtypes

### ISSUE THREAD

**Issue by sjoerdvisscher** [natefaubion/purescript-routing-duplex#13]
Hi, I found the following useful:

```purescript
newtype_ :: forall a b. Newtype a b => RouteDuplex' b -> RouteDuplex' a
newtype_ = dimap unwrap wrap
```

Maybe you want to consider adding this to the library?

**Comment by JordanMartinez** [comment]
That's already defined in `purescript-newtype`.

**Comment by natefaubion** [comment]
It's actually `_Newtype` in `purescript-profunctor-optics`
https://pursuit.purescript.org/packages/purescript-profunctor-lenses/6.2.0/docs/Data.Lens.Iso.Newtype#v:_Newtype

This library will work with any `Iso`. It doesn't have `Strong` or `Choice` instances though, so it doesn't work with lenses or prisms in general.

**Comment by sjoerdvisscher** [comment]
Ah of course! Thanks.

I think `Strong` and `Choice` instances should be possible though! Not sure if that would be useful.

**Comment by sjoerdvisscher** [comment]
Hmm, the type of `_Newtype` is too flexible, so it can't be used without a type signature.

**Comment by natefaubion** [comment]
The generality of `_Newtype` is _often_ a problem, and not just here. There should be a non-type changing version of it.
