### ISSUE TITLE
Please add repository to bower.json for subsequent publishing to Pursuit

### ISSUE THREAD

**Issue by cscalfani** [natefaubion/purescript-routing-duplex#18]
I published this package to Pursuit but it was missing the following from `bower.json`:

```json
"repository": {
      "type": "git",
      "url": "https://github.com/natefaubion/purescript-routing-duplex.git"
    }
```

I had to add it locally and then move the tag so that I could publish this package. Adding this will make it easy for subsequent publishing.

**Comment by natefaubion** [comment]
This isn't necessary anymore.
