### ISSUE TITLE
Failed pattern match for invalid URL encoded path

### ISSUE THREAD

**Issue by dederer** [natefaubion/purescript-routing-duplex#27]
In production, I got a runtime error in the `parsePath` function from the `Routing.Duplex.Parser` module:

```
stack: Error: Failed pattern match at Data.Maybe (line 281, column 1 - line 281, column 46): Nothing
```

The reason for the error is an invalid URL encoded string "%D0%BF%D0".

For example, this command results in an error:

```purs
parsePath "https://example.com?keyword=%D0%BF%D0"
```

**Comment by natefaubion** [comment]
Yeah, we need to remove the unsafe usage here:
https://github.com/natefaubion/purescript-routing-duplex/blob/f4430e60d6519b5c43a888cf153dddee0cbc2946/src/Routing/Duplex/Parser.purs#L166
