### ISSUE TITLE
optional/default are not wokring with segment

### ISSUE THREAD

**Issue by yaitskov** [natefaubion/purescript-routing-duplex#36]
Hi,

It seems `segment` never fails and return empty string in case of failure.
`optional` and `default` break because of this.

**Comment by natefaubion** [comment]
Can you post a try.purescript.org reproduction? I believe you have misdiagnosed your issue. `segment` is `Parser.take`, which does not operate the way you are describing.
https://github.com/natefaubion/purescript-routing-duplex/blob/13702d4a73ac3eac1d8c09701fb06faca7073728/src/Routing/Duplex/Parser.purs#L207-L211

**Comment by yaitskov** [comment]
Yep the issue happens not always, but only when segment is empty.
So `default "expect" segment` works for parsing empty string but not "/"
If route is a complex object it contains multiple segments. 
So following paths "/////" "/" "////" produce different Routes.

 
https://try.purescript.org/?code=LTBQFsHsBMFcBsCmACAsgQwJYDtkHcALRAJ0VHM3AAdJiAXZABVPlmhQM2hwHNkAKfgHoAlCIrVaDACLo66AHQBlApDwKA4omwlMAY1CUa9ZLPmbtuvQoBKiKockmbkWHV4LpsKkgAej4wYXNw8vH0RfZHQAZ2QbaQCpONd3bB5Pbz8LHWJ9ROcU0MyI7KtlAE9seX8jJIBRADMGxD06BQBhSGxoyCR8mTlFAEFiYnRyqNih-tNB5TpctMnkJRmzRSUFj07wKFwYlbW55kgG2GxW2mRycHRiaIJ0eGQALhfQZGS3RDC-AHIVlslsAAHwfL50H7FXwAgCSVQgdweT2QAF5kNxblRkA1kDxwYQSGRPp9cejtHoYMSSXx0VQkWRyPT7ig3oDFnxQch4XRQMzoih0UoFEg0nQCOQKVTXi9uVVkFzNhzQFL2MhcEKFAArSA4ADqmHFyAARMbkAASZBDBSkHz6OQoXDG4DG8iInBojGQcHwSB8S0PNQCeIKfkofgh9gNdAIBjGuq%2BKgtSHQM0CnjgbR0EQmoTG8SfX3%2Bk0RJOtRDQZAAdmQACM3HjIAwAAyys0AHhByEDeGD0lDDL7CijMfgDBr-Fu90ez3TmaqYlz%2Bbd5E%2B4PBQA

**Comment by natefaubion** [comment]
That is expected. Internally we do not normalize paths, as this is no longer bidirectional from the source input. If you have a leading `/`, then that's what the `root` combinator is for. You can choose to implement normalization yourself (you may not care about strict bidirectionality) by constructing your own pass on top of `parsePath`.

https://github.com/natefaubion/purescript-routing-duplex/blob/master/src/Routing/Duplex/Parser.purs#L164
